### ISSUE TITLE
This template is not mobile friendly?

### ISSUE THREAD

**Issue by whynesspower** [ixartz/SaaS-Boilerplate#11]
![image](https://github.com/ixartz/SaaS-Boilerplate/assets/77494053/5cdf26fc-5454-485c-8343-f5ac83cd0258)
The template is simply not mobile compatible at all. Navbar breaks, image breaks

**Comment by ixartz** [comment]
Indeed, it should be easy fix, just didn't find the time to make it right. It should only need 2/3 tailwind css classes and it should be fixed.

I'll fix it next week

**Comment by ixartz** [comment]
FYI, the SaaS Boilerplate is now fully responsive 🎉

You can find the PR at https://github.com/ixartz/SaaS-Boilerplate/pull/13, it also includes various little changes
