### ISSUE TITLE
Stripe integration

### ISSUE THREAD

**Issue by nhwebforge** [ixartz/SaaS-Boilerplate#15]
Hi! First off, great work! Looks and works awesome!
I notice in the .env there is a placeholder for Stripe API keys. Is this feature available or is it in the pipeline? Can't seem to find any reference to it.
Thanks again
NH

**Comment by ixartz** [comment]
Hi, thank you so much for your comment.

Yes, in the future, I'll add the Stripe integration into the project.

Currently, it's only available at https://nextjs-boilerplate.com/pro-saas-starter-kit.

It'll also make this project viable in the long term. I'm planning to support this SaaS Boilerplate for several years. FYI, I have already maintained Next.js Boilerplate for more than 3 years.
