### ISSUE TITLE
Turborepo

### ISSUE THREAD

**Issue by hsavit1** [ixartz/SaaS-Boilerplate#18]
Can you add turborepo to this starter?

**Comment by ixartz** [comment]
Is there any reason to add turborepo?

I want to keep the project easy to start and easy to begin with.

**Comment by hsavit1** [comment]
At this point in 2024 if you're a startup I'd recommend starting a project with Turborepo. It's likely that as a startup that you will need multiple applications and turborepo makes it easiest to have multiple applications. It's easier to start with turborepo rather than having to migrate a codebase into it later on.

**Comment by ixartz** [comment]
Indeed, if you need to have multiple application, Turborepo makes it easier.

The project has only one application and currently, there is no plan to have multiple applications. I'll try my best to have one programming language, one framework, one application, etc.

**Comment by garysassano** [comment]
I think now it would actually be a good time in case you wanted to implement such feature: https://turbo.build/blog/turbo-2-0

**Comment by garysassano** [comment]
I think now it would actually be a good time in case you wanted to implement such feature, as [Turborepo 2.0 just got released](https://turbo.build/blog/turbo-2-0).

**Comment by ixartz** [comment]
It's a good time to add the feature but currently not very convince about adding it, it would add more complexity into the project.

And what will be the use case? In the current state or future state, what Turborepo will bring into the project?
Not a huge fan to add a tech, just for adding it.
