### ISSUE TITLE
error when using pnpm

### ISSUE THREAD

**Issue by garysassano** [ixartz/SaaS-Boilerplate#22]
After cloning the repo and executing `pnpm dev`, you get the following error:

```sh
> saas-boilerplate@1.4.0 dev /home/user/github/SaaS-Boilerplate
> run-p dev:*

 ERROR  Unknown option: 'saas-boilerplate:commitizen_path'
For help, run: pnpm help run
 ERROR  Unknown option: 'saas-boilerplate:commitizen_path'
For help, run: pnpm help run
ERROR: "dev:spotlight" exited with 1.
 ELIFECYCLE  Command failed with exit code 1.
```

`npm run dev` works fine on the other hand. Even though I don't see why anyone would still use npm in 2024.

**Comment by ixartz** [comment]
The project is built and tested on NPM, the documentation suggests NPM and it uses the NPM lock file.

As you confirmed, the project doesn't work on PNPM. But I'm also very surprised it didn't work on PNPM, there isn't any specific feature for NPM. In theory, it should also work on PNPM.

That being said, I only focus on NPM. I have limited resources and it's impossible for me to maintain for `yarn`, `pnpm`, or `bun`. I choose the most support package manager, which is NPM. Of course, you can use other package manager but the default one is NPM.

So, I'm totally open to PR to make it work on PNPM. But the project focuses on NPM.
