### ISSUE TITLE
Why Drizzle ORM and not Prisma DRM? (need support for MongoDB)

### ISSUE THREAD

**Issue by avibathula** [ixartz/SaaS-Boilerplate#35]
Hi - what is the reasoning behind the architecture design choice of picking Drizzle ORM instead of Prisma DRM?

I need to use MongoDB for my use case and from Drizzle ORM doesn't support no-SQL.

Regards,
   -Avi

**Comment by ixartz** [comment]
Hi, here is why the project choose Drizzle ORM instead of Prisma:
Schema in TypeScript
No DB client to generate
Programmatic migrate function
Config file.
