### ISSUE TITLE
Guidance of what Product Analytics suite (PostHog etc.) with SaaS-Boilerplate

### ISSUE THREAD

**Issue by avibathula** [ixartz/SaaS-Boilerplate#36]
When using SaaS-Boilerplate, what Product Analytics suite (PostHog etc.) are any of you using?

**Comment by ixartz** [comment]
Yes, [PostHog](https://posthog.com/?utm_source=github&utm_medium=sponsorship&utm_campaign=next-js-boilerplate) works with the project.
