### ISSUE TITLE
Feature Request: Any system & user driven dark/light theme support using next-themes library

### ISSUE THREAD

**Issue by avibathula** [ixartz/SaaS-Boilerplate#40]
https://dev.to/sujit-shrc/implementing-dark-and-light-themes-in-nextjs-13-with-tailwind-css-57l5

**Comment by ixartz** [comment]
Duplicate of https://github.com/ixartz/SaaS-Boilerplate/issues/29

**Comment by ixartz** [comment]
Just implemented and released a dark mode, there is a live demo at: https://pro-demo.nextjs-boilerplate.com
