### ISSUE TITLE
Env.ts comment "// Don't add NODE_ENV into T3 Env, it changes the tree-shaking behavior"

### ISSUE THREAD

**Issue by avibathula** [ixartz/SaaS-Boilerplate#45]
Env.ts has a comment saying

"// Don't add NODE_ENV into T3 Env, it changes the tree-shaking behavior"

But, I see the flag has been added to `shared` property object.

So, was the comment supposed to be removed some time back? - if so, how does the project deal with "tree shaking" impact of NODE_ENV?

Or

Was the addition of the flag a mistake?

**Comment by ixartz** [comment]
If I remember well, it used to have warning in the official documentation of `t3 env` related to NODE_ENV.

After some quick research, it seems the comment has been removed, I suppose the issue has been fixed.

I'm planning to remove this comment.
