### ISSUE TITLE
Clerk Error in production

### ISSUE THREAD

**Issue by mmaksi** [ixartz/SaaS-Boilerplate#47]
My code works perfectly fine in development but when deployed to production, it gives this error whenever I try to login: `Clerk: Failed to load Clerk`

I provided the production NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY and CLERK_SECRET_KEY.

But I still didn't provide a database, Stripe API key and other environment variables.

**Comment by ixartz** [comment]
@mmaksi thank you for opening the issue. It should work out of the box, you shouldn't need to make any changes for supporting Clerk, everything is configured for you. You just make sure the environment variables are correct.

Are you sure the environment variables are loaded in production?

**Comment by ixartz** [comment]
No response, I'm closing it
