### ISSUE TITLE
Is there a way to disable `Organization` during onboarding

### ISSUE THREAD

**Issue by CharlesCCC** [ixartz/SaaS-Boilerplate#55]
Hi Team, thank you for create this great project. 

I noticed right now the sign-up/sign-in will automatically redirect to `organization` creation flow. (which is not necessary needed fro every SaaS). Is there a way to disable it now ? (or I might have PR that myself) ? 

thank you

**Comment by ixartz** [comment]
Hi,

Here is the documentation to force organization: https://clerk.com/docs/guides/force-organizations#hide-personal-accounts-from-ui-components
In your case, you need to do the opposite.

**Comment by collasanta** [comment]
I managed to do it by disabling organizations on Clerk, and commenting out: 

this in middleware.ts 

      // if (
      //   authObj.userId
      //   && !authObj.orgId
      //   && req.nextUrl.pathname.includes('/dashboard')
      //   && !req.nextUrl.pathname.endsWith('/organization-selection')
      // ) {
      //   const orgSelection = new URL(
      //     '/onboarding/organization-selection',
      //     req.url,
      //   );

      //   return NextResponse.redirect(orgSelection);
      // }
      
 and this in DashboardHeader.tsx 
 
         {/* <OrganizationSwitcher
          organizationProfileMode="navigation"
          organizationProfileUrl={getI18nPath(
            '/dashboard/organization-profile',
            locale,
          )}
          afterCreateOrganizationUrl="/dashboard"
          hidePersonal
          skipInvitationScreen
          appearance={{
            elements: {
              organizationSwitcherTrigger: 'max-w-28 sm:max-w-52',
            },
          }}
        /> */}

**Comment by Sher-Chowdhury** [comment]
Hi @ixartz,
I tried making those changes. I ended up changing this in two places:
 

<img width="1438" alt="Image" src="https://github.com/user-attachments/assets/1ad73626-2005-423d-962a-71b2e3c0e7af" />

and:

<img width="1567" alt="Image" src="https://github.com/user-attachments/assets/155dbc94-34a8-4b85-b432-97397cc1c78c" />

Now I get something a little different (after getting redirected back from Google authentication):


<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/672fe719-901b-4950-95ce-a2cf989c9bf2" />
 

There's 2 problems here:
1. I want users to go straight to the dashboard page, therefore I wanted to hide this "Choose an account" ui. 
2. Clicking on "Personal account" doesn't appear to do anything. 

Do you know if there's anything else I need to change to get past this?

Also I support the idea of a env var for toggling organisations off/on.
