### ISSUE TITLE
when globe button is clicked, it hides the scroll bar and flickers.

### ISSUE THREAD

**Issue by kaleb110** [ixartz/SaaS-Boilerplate#56]
when switching between languages , it hides the scroll bar and reapears again.

**Comment by ixartz** [comment]
It seems to be a temporary issue and we don't have the issue here: https://pro-demo.nextjs-boilerplate.com

It'll be resolved in the update of SaaS Boilerplate.

**Comment by ixartz** [comment]
Thank you @kaleb110 for reporting it!
